export const project = {
  meta: {
    name: 'Sector Demo',
    schemaVersion: 3,
    renderMode: '3d',
  },
  camera: {
    posX: 2.0,
    posY: 3.0,
    posZ: 0.6,
    yaw: 0,
    pitch: 0,
  },
  world: {
    vertices: [
      { id: 'v0', x: 0, y: 0 },
      { id: 'v1', x: 6, y: 0 },
      { id: 'v2', x: 7, y: 0 },
      { id: 'v3', x: 8, y: 0 },
      { id: 'v4', x: 9, y: 0 },
      { id: 'v5', x: 10, y: 0 },
      { id: 'v6', x: 0, y: 6 },
      { id: 'v7', x: 6, y: 6 },
      { id: 'v8', x: 7, y: 6 },
      { id: 'v9', x: 8, y: 6 },
      { id: 'v10', x: 9, y: 6 },
      { id: 'v11', x: 10, y: 6 },
      { id: 'v12', x: 16, y: 0 },
      { id: 'v13', x: 17, y: 0 },
      { id: 'v14', x: 18, y: 0 },
      { id: 'v15', x: 19, y: 0 },
      { id: 'v16', x: 20, y: 0 },
      { id: 'v17', x: 26, y: 0 },
      { id: 'v18', x: 16, y: 6 },
      { id: 'v19', x: 17, y: 6 },
      { id: 'v20', x: 18, y: 6 },
      { id: 'v21', x: 19, y: 6 },
      { id: 'v22', x: 20, y: 6 },
      { id: 'v23', x: 26, y: 6 },
    ],
    sectors: [
      {
        id: 's0',
        vertexIds: ['v0', 'v1', 'v7', 'v6'],
        floorH: 0.0,
        ceilH: 4.0,
        floorTex: 'floor',
        ceilTex: 'ceil',
        wallTex: 'wall',
      },
      // Rampa irregular de subida
      {
        id: 's1',
        vertexIds: ['v1', 'v2', 'v8', 'v7'],
        floorH: [0.0, 0.4, 0.5, 0.3],
        ceilH: 4.0,
        floorTex: 'floor',
        ceilTex: 'ceil',
        wallTex: 'wall',
      },
      {
        id: 's2',
        vertexIds: ['v2', 'v3', 'v9', 'v8'],
        floorH: [0.4, 0.9, 1.0, 0.8],
        ceilH: 4.0,
        floorTex: 'floor',
        ceilTex: 'ceil',
        wallTex: 'wall',
      },
      {
        id: 's3',
        vertexIds: ['v3', 'v4', 'v10', 'v9'],
        floorH: [0.9, 1.6, 1.8, 1.4],
        ceilH: 4.0,
        floorTex: 'floor',
        ceilTex: 'ceil',
        wallTex: 'wall',
      },
      {
        id: 's4',
        vertexIds: ['v4', 'v5', 'v11', 'v10'],
        floorH: [1.6, 2.3, 2.5, 2.0],
        ceilH: 4.0,
        floorTex: 'floor',
        ceilTex: 'ceil',
        wallTex: 'wall',
      },
      // Plataforma alta
      {
        id: 's5',
        vertexIds: ['v5', 'v12', 'v18', 'v11'],
        floorH: 2.3,
        ceilH: 6.0,
        floorTex: 'floor',
        ceilTex: 'ceil',
        wallTex: 'wall',
      },
      // Rampa irregular de bajada
      {
        id: 's6',
        vertexIds: ['v12', 'v13', 'v19', 'v18'],
        floorH: [2.3, 2.0, 2.2, 2.4],
        ceilH: 6.0,
        floorTex: 'floor',
        ceilTex: 'ceil',
        wallTex: 'wall',
      },
      {
        id: 's7',
        vertexIds: ['v13', 'v14', 'v20', 'v19'],
        floorH: [2.0, 1.5, 1.7, 1.9],
        ceilH: 6.0,
        floorTex: 'floor',
        ceilTex: 'ceil',
        wallTex: 'wall',
      },
      {
        id: 's8',
        vertexIds: ['v14', 'v15', 'v21', 'v20'],
        floorH: [1.5, 0.9, 1.1, 1.3],
        ceilH: 6.0,
        floorTex: 'floor',
        ceilTex: 'ceil',
        wallTex: 'wall',
      },
      {
        id: 's9',
        vertexIds: ['v15', 'v16', 'v22', 'v21'],
        floorH: [0.9, 0.2, 0.4, 0.6],
        ceilH: 6.0,
        floorTex: 'floor',
        ceilTex: 'ceil',
        wallTex: 'wall',
      },
      // Sala final
      {
        id: 's10',
        vertexIds: ['v16', 'v17', 'v23', 'v22'],
        floorH: 0.0,
        ceilH: 4.0,
        floorTex: 'floor',
        ceilTex: 'ceil',
        wallTex: 'wall',
      },
    ],
    walls: [
      // s0
      { id: 'w0', a: 'v0', b: 'v1', sectorFront: 's0', sectorBack: null, tex: 'wall' },
      { id: 'w1', a: 'v1', b: 'v7', sectorFront: 's0', sectorBack: 's1', tex: 'wall', portal: true },
      { id: 'w2', a: 'v7', b: 'v6', sectorFront: 's0', sectorBack: null, tex: 'wall' },
      { id: 'w3', a: 'v6', b: 'v0', sectorFront: 's0', sectorBack: null, tex: 'wall' },
      // s1
      { id: 'w4', a: 'v1', b: 'v2', sectorFront: 's1', sectorBack: null, tex: 'wall' },
      { id: 'w5', a: 'v2', b: 'v8', sectorFront: 's1', sectorBack: 's2', tex: 'wall', portal: true },
      { id: 'w6', a: 'v8', b: 'v7', sectorFront: 's1', sectorBack: null, tex: 'wall' },
      // s2
      { id: 'w7', a: 'v2', b: 'v3', sectorFront: 's2', sectorBack: null, tex: 'wall' },
      { id: 'w8', a: 'v3', b: 'v9', sectorFront: 's2', sectorBack: 's3', tex: 'wall', portal: true },
      { id: 'w9', a: 'v9', b: 'v8', sectorFront: 's2', sectorBack: null, tex: 'wall' },
      // s3
      { id: 'w10', a: 'v3', b: 'v4', sectorFront: 's3', sectorBack: null, tex: 'wall' },
      { id: 'w11', a: 'v4', b: 'v10', sectorFront: 's3', sectorBack: 's4', tex: 'wall', portal: true },
      { id: 'w12', a: 'v10', b: 'v9', sectorFront: 's3', sectorBack: null, tex: 'wall' },
      // s4
      { id: 'w13', a: 'v4', b: 'v5', sectorFront: 's4', sectorBack: null, tex: 'wall' },
      { id: 'w14', a: 'v5', b: 'v11', sectorFront: 's4', sectorBack: 's5', tex: 'wall', portal: true },
      { id: 'w15', a: 'v11', b: 'v10', sectorFront: 's4', sectorBack: null, tex: 'wall' },
      // s5
      { id: 'w16', a: 'v5', b: 'v12', sectorFront: 's5', sectorBack: null, tex: 'wall' },
      { id: 'w17', a: 'v12', b: 'v18', sectorFront: 's5', sectorBack: 's6', tex: 'wall', portal: true },
      { id: 'w18', a: 'v18', b: 'v11', sectorFront: 's5', sectorBack: null, tex: 'wall' },
      // s6
      { id: 'w19', a: 'v12', b: 'v13', sectorFront: 's6', sectorBack: null, tex: 'wall' },
      { id: 'w20', a: 'v13', b: 'v19', sectorFront: 's6', sectorBack: 's7', tex: 'wall', portal: true },
      { id: 'w21', a: 'v19', b: 'v18', sectorFront: 's6', sectorBack: null, tex: 'wall' },
      // s7
      { id: 'w22', a: 'v13', b: 'v14', sectorFront: 's7', sectorBack: null, tex: 'wall' },
      { id: 'w23', a: 'v14', b: 'v20', sectorFront: 's7', sectorBack: 's8', tex: 'wall', portal: true },
      { id: 'w24', a: 'v20', b: 'v19', sectorFront: 's7', sectorBack: null, tex: 'wall' },
      // s8
      { id: 'w25', a: 'v14', b: 'v15', sectorFront: 's8', sectorBack: null, tex: 'wall' },
      { id: 'w26', a: 'v15', b: 'v21', sectorFront: 's8', sectorBack: 's9', tex: 'wall', portal: true },
      { id: 'w27', a: 'v21', b: 'v20', sectorFront: 's8', sectorBack: null, tex: 'wall' },
      // s9
      { id: 'w28', a: 'v15', b: 'v16', sectorFront: 's9', sectorBack: null, tex: 'wall' },
      { id: 'w29', a: 'v16', b: 'v22', sectorFront: 's9', sectorBack: 's10', tex: 'wall', portal: true },
      { id: 'w30', a: 'v22', b: 'v21', sectorFront: 's9', sectorBack: null, tex: 'wall' },
      // s10
      { id: 'w31', a: 'v16', b: 'v17', sectorFront: 's10', sectorBack: null, tex: 'wall' },
      { id: 'w32', a: 'v17', b: 'v23', sectorFront: 's10', sectorBack: null, tex: 'wall' },
      { id: 'w33', a: 'v23', b: 'v22', sectorFront: 's10', sectorBack: null, tex: 'wall' },
    ],
    ramps: [
      {
        id: 'r0',
        sectorId: 's0',
        type: 'stairs',
        pos: { x: 1, y: 1 },
        direction: { x: 1, y: 0 },
        width: 1,
        rise: 1.0,
        run: 2.0,
        steps: 4,
        tex: 'stair',
      },
    ],
    sprites: [
      {
        id: 'sp0',
        tex: 'sprite',
        pos: { x: 3, y: 3, z: 0.6 },
        scale: 1.0,
        billboard: true,
      },
    ],
    textures: {
      wall: './textures/muro.svg',
      floor: './textures/suelo1.svg',
      ceil: './textures/techo.svg',
      stair: './textures/suelo2.svg',
      sprite: './textures/azul.svg',
    },
  },
};
